public enum AttractorType {
	AIZAWA, BOUALI, CHENCELIKOVSKY, CHENLEE, HADLEY, HALVORSEN, IKEDA, LIUCHEN, LORENZ, LUCHEN, NOSEHOOVER, PICKOVER, QICHEN, RAYLEIGHBENARD, ROSSLER, THOMAS, TSUCS1, TSUCS2, ZHOUCHEN
}